### ISSUE TITLE
linker error when compiling from source -- seems to not be  -lopengl32 ?

### ISSUE THREAD

**Issue by oschonrock** [WerWolv/ImHex#1905]
### Operating System

Linux

### What's the issue you encountered?

Linker error:

```
[295/551] Linking CXX executable imhex-updater
FAILED: imhex-updater 
: && /usr/bin/g++-13 -O3 -DNDEBUG  main/updater/CMakeFiles/updater.dir/source/main.cpp.o -o imhex-updater  -Wl,-rpath,/home/oliver/c/ImHex/build/lib/libimhex:  lib/libimhex/libimhex.so.1.36.0.WIP  /usr/lib/x86_64-linux-gnu/libcurl.so  lib/external/pattern_language/lib/libpl.a  lib/external/libwolv/libs/io/liblibwolv-io.a  lib/external/libwolv/libs/utils/libwolv-utils.a  /usr/lib/x86_64-linux-gnu/libfreetype.so  /usr/lib/x86_64-linux-gnu/libOpenGL.so  /usr/lib/x86_64-linux-gnu/libGLX.so  /usr/lib/x86_64-linux-gnu/libGLU.so  -L/usr/lib/x86_64-linux-gnu -lmbedtls -lmbedx509 -lmbedcrypto  lib/third_party/lunasvg/liblunasvg.a && :
/usr/bin/ld: lib/libimhex/libimhex.so.1.36.0.WIP: undefined reference to `glfwDestroyCursor'
/usr/bin/ld: lib/libimhex/libimhex.so.1.36.0.WIP: undefined reference to `glfwCreateWindow'
/usr/bin/ld: lib/libimhex/libimhex.so.1.36.0.WIP: undefined reference to `glfwSetWindowPosCallback'
/usr/bin/ld: lib/libimhex/libimhex.so.1.36.0.WIP: undefined reference to `glfwGetWindowSize'
...
```

### How can the issue be reproduced?

follow these instructions on ubuntu 22.04

https://github.com/WerWolv/ImHex/blob/master/dist/compiling/linux.md

### ImHex Version

master

### ImHex Build Type

- [X] Nightly or built from sources

### Installation type

compile from source

### Additional context?

deps were installed as per

https://github.com/WerWolv/ImHex/blob/master/dist/get_deps_debian.sh

missing `-l` or a lib version difference?

**Comment by WerWolv** [comment]
Hey! It looks like it's not linking against glfw correctly on your machine (or against an old version of it perhaps). Do you have it installed? It seems to work fine in our Ubuntu 22.04 CI runner so I believe this is a setup issue on your side.

**Comment by oschonrock** [comment]
yes.. 

problem now resolved... it was an unclean build. 

removing build dir and rebuilding from scratch resolved it. 

closing.
