### ISSUE TITLE
[Bug] ImHex doesn't compile under MacOS 10.15.7

### ISSUE THREAD

**Issue by Aniruddha-Deb** [WerWolv/ImHex#755]
### Operating System

MacOS

### What's the issue you encountered?

Building on MacOS 10.15 using the steps described [here](https://github.com/WerWolv/ImHex/blob/master/dist/compiling/macOS.md), the build fails at 84% with the following error messages:
```
[ 84%] Building CXX object plugins/builtin/CMakeFiles/builtin.dir/source/content/views/view_disassembler.cpp.o
/Users/Sensei/OpenSource/ImHex/plugins/builtin/source/content/views/view_disassembler.cpp: In member function 'virtual void hex::plugin::builtin::ViewDisassembler::drawContent()':
/Users/Sensei/OpenSource/ImHex/plugins/builtin/source/content/views/view_disassembler.cpp:196:105: error: 'CS_MODE_SPE' was not declared in this scope; did you mean 'CS_MODE_QPX'?
  196 |                                 this->m_mode = cs_mode(mode | (qpx ? CS_MODE_QPX : cs_mode(0)) | (spe ? CS_MODE_SPE : cs_mode(0)) | (booke ? CS_MODE_BOOKE : cs_mode(0)));
      |                                                                                                         ^~~~~~~~~~~
      |                                                                                                         CS_MODE_QPX
/Users/Sensei/OpenSource/ImHex/plugins/builtin/source/content/views/view_disassembler.cpp:196:142: error: 'CS_MODE_BOOKE' was not declared in this scope; did you mean 'CS_MODE_V9'?
  196 |                                 this->m_mode = cs_mode(mode | (qpx ? CS_MODE_QPX : cs_mode(0)) | (spe ? CS_MODE_SPE : cs_mode(0)) | (booke ? CS_MODE_BOOKE : cs_mode(0)));
      |                                                                                                                                              ^~~~~~~~~~~~~
      |                                                                                                                                              CS_MODE_V9
/Users/Sensei/OpenSource/ImHex/plugins/builtin/source/content/views/view_disassembler.cpp:209:51: error: 'CS_MODE_RISCV32' was not declared in this scope; did you mean 'CS_MODE_MIPS32'?
  209 |                                 static int mode = CS_MODE_RISCV32;
      |                                                   ^~~~~~~~~~~~~~~
      |                                                   CS_MODE_MIPS32
/Users/Sensei/OpenSource/ImHex/plugins/builtin/source/content/views/view_disassembler.cpp:212:103: error: 'CS_MODE_RISCV64' was not declared in this scope; did you mean 'CS_MODE_MIPS64'?
  212 |                                 ImGui::RadioButton("hex.builtin.view.disassembler.64bit"_lang, &mode, CS_MODE_RISCV64);
      |                                                                                                       ^~~~~~~~~~~~~~~
      |                                                                                                       CS_MODE_MIPS64
/Users/Sensei/OpenSource/ImHex/plugins/builtin/source/content/views/view_disassembler.cpp:217:77: error: 'CS_MODE_RISCVC' was not declared in this scope; did you mean 'CS_MODE_MICRO'?
  217 |                                 this->m_mode = cs_mode(mode | (compressed ? CS_MODE_RISCVC : cs_mode(0)));
      |                                                                             ^~~~~~~~~~~~~~
      |                                                                             CS_MODE_MICRO
/Users/Sensei/OpenSource/ImHex/plugins/builtin/source/content/views/view_disassembler.cpp:277:99: error: 'CS_MODE_MOS65XX_6502' was not declared in this scope; did you mean 'CS_MODE_M680X_6809'?
  277 |                                     {"hex.builtin.view.disassembler.mos65xx.6502"_lang,           CS_MODE_MOS65XX_6502         },
      |                                                                                                   ^~~~~~~~~~~~~~~~~~~~
      |                                                                                                   CS_MODE_M680X_6809
/Users/Sensei/OpenSource/ImHex/plugins/builtin/source/content/views/view_disassembler.cpp:278:99: error: 'CS_MODE_MOS65XX_65C02' was not declared in this scope; did you mean 'CS_MODE_M680X_6809'?
  278 |                                     { "hex.builtin.view.disassembler.mos65xx.65c02"_lang,         CS_MODE_MOS65XX_65C02        },
      |                                                                                                   ^~~~~~~~~~~~~~~~~~~~~
      |                                                                                                   CS_MODE_M680X_6809
/Users/Sensei/OpenSource/ImHex/plugins/builtin/source/content/views/view_disassembler.cpp:279:99: error: 'CS_MODE_MOS65XX_W65C02' was not declared in this scope; did you mean 'CS_MODE_M680X_6809'?
  279 |                                     { "hex.builtin.view.disassembler.mos65xx.w65c02"_lang,        CS_MODE_MOS65XX_W65C02       },
      |                                                                                                   ^~~~~~~~~~~~~~~~~~~~~~
      |                                                                                                   CS_MODE_M680X_6809
/Users/Sensei/OpenSource/ImHex/plugins/builtin/source/content/views/view_disassembler.cpp:280:99: error: 'CS_MODE_MOS65XX_65816' was not declared in this scope; did you mean 'CS_MODE_M680X_6811'?
  280 |                                     { "hex.builtin.view.disassembler.mos65xx.65816"_lang,         CS_MODE_MOS65XX_65816        },
      |                                                                                                   ^~~~~~~~~~~~~~~~~~~~~
      |                                                                                                   CS_MODE_M680X_6811
/Users/Sensei/OpenSource/ImHex/plugins/builtin/source/content/views/view_disassembler.cpp:281:99: error: 'CS_MODE_MOS65XX_65816_LONG_M' was not declared in this scope
  281 |                                     { "hex.builtin.view.disassembler.mos65xx.65816_long_m"_lang,  CS_MODE_MOS65XX_65816_LONG_M },
      |                                                                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/Sensei/OpenSource/ImHex/plugins/builtin/source/content/views/view_disassembler.cpp:282:99: error: 'CS_MODE_MOS65XX_65816_LONG_X' was not declared in this scope
  282 |                                     { "hex.builtin.view.disassembler.mos65xx.65816_long_x"_lang,  CS_MODE_MOS65XX_65816_LONG_X },
      |                                                                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/Sensei/OpenSource/ImHex/plugins/builtin/source/content/views/view_disassembler.cpp:283:99: error: 'CS_MODE_MOS65XX_65816_LONG_MX' was not declared in this scope
  283 |                                     { "hex.builtin.view.disassembler.mos65xx.65816_long_mx"_lang, CS_MODE_MOS65XX_65816_LONG_MX},
      |                                                                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/Sensei/OpenSource/ImHex/plugins/builtin/source/content/views/view_disassembler.cpp:284:33: error: could not convert '{hex::operator""_lang(const char*, size_t)(42), <expression error>}' from '<brace-enclosed initializer list>' to 'std::pair<const char*, cs_mode>'
  284 |                                 };
      |                                 ^
      |                                 |
      |                                 <brace-enclosed initializer list>
/Users/Sensei/OpenSource/ImHex/plugins/builtin/source/content/views/view_disassembler.cpp:284:33: error: could not convert '{hex::operator""_lang(const char*, size_t)(43), <expression error>}' from '<brace-enclosed initializer list>' to 'std::pair<const char*, cs_mode>'
  284 |                                 };
      |                                 ^
      |                                 |
      |                                 <brace-enclosed initializer list>
/Users/Sensei/OpenSource/ImHex/plugins/builtin/source/content/views/view_disassembler.cpp:284:33: error: could not convert '{hex::operator""_lang(const char*, size_t)(44), <expression error>}' from '<brace-enclosed initializer list>' to 'std::pair<const char*, cs_mode>'
  284 |                                 };
      |                                 ^
      |                                 |
      |                                 <brace-enclosed initializer list>
/Users/Sensei/OpenSource/ImHex/plugins/builtin/source/content/views/view_disassembler.cpp:284:33: error: could not convert '{hex::operator""_lang(const char*, size_t)(43), <expression error>}' from '<brace-enclosed initializer list>' to 'std::pair<const char*, cs_mode>'
  284 |                                 };
      |                                 ^
      |                                 |
      |                                 <brace-enclosed initializer list>
/Users/Sensei/OpenSource/ImHex/plugins/builtin/source/content/views/view_disassembler.cpp:284:33: error: could not convert '{hex::operator""_lang(const char*, size_t)(50), <expression error>}' from '<brace-enclosed initializer list>' to 'std::pair<const char*, cs_mode>'
  284 |                                 };
      |                                 ^
      |                                 |
      |                                 <brace-enclosed initializer list>
/Users/Sensei/OpenSource/ImHex/plugins/builtin/source/content/views/view_disassembler.cpp:284:33: error: could not convert '{hex::operator""_lang(const char*, size_t)(50), <expression error>}' from '<brace-enclosed initializer list>' to 'std::pair<const char*, cs_mode>'
  284 |                                 };
      |                                 ^
      |                                 |
      |                                 <brace-enclosed initializer list>
/Users/Sensei/OpenSource/ImHex/plugins/builtin/source/content/views/view_disassembler.cpp:284:33: error: could not convert '{hex::operator""_lang(const char*, size_t)(51), <expression error>}' from '<brace-enclosed initializer list>' to 'std::pair<const char*, cs_mode>'
  284 |                                 };
      |                                 ^
      |                                 |
      |                                 <brace-enclosed initializer list>
/Users/Sensei/OpenSource/ImHex/plugins/builtin/source/content/views/view_disassembler.cpp:299:51: error: 'CS_MODE_BPF_CLASSIC' was not declared in this scope; did you mean 'CS_MODE_MCLASS'?
  299 |                                 static int mode = CS_MODE_BPF_CLASSIC;
      |                                                   ^~~~~~~~~~~~~~~~~~~
      |                                                   CS_MODE_MCLASS
/Users/Sensei/OpenSource/ImHex/plugins/builtin/source/content/views/view_disassembler.cpp:302:110: error: 'CS_MODE_BPF_EXTENDED' was not declared in this scope
  302 |                                 ImGui::RadioButton("hex.builtin.view.disassembler.bpf.extended"_lang, &mode, CS_MODE_BPF_EXTENDED);
      |                                                                                                              ^~~~~~~~~~~~~~~~~~~~
make[2]: *** [plugins/builtin/CMakeFiles/builtin.dir/source/content/views/view_disassembler.cpp.o] Error 1
make[1]: *** [plugins/builtin/CMakeFiles/builtin.dir/all] Error 2
make: *** [all] Error 2
```

XCode CLT, as well as all the required brew libraries are installed. Output of `brew doctor`:

### How can the issue be reproduced?

Compile on MacOS 10.15 using the same steps described above

### ImHex Version

1.23.2 (#f52dae42976e646726ee87bc4ce3afae3a91a8ae)

### ImHex Build Type

- [X] Nightly or built from sources

### Additional context?

g++-12 v.12.2.0, llvm v.15.0.1, pkgconfig v.0.29.2

**Comment by WerWolv** [comment]
Hey
This looks like you have a older version of Capstone installed on your system and your environment seems to prefer it over the one that's bundled with ImHex. Make sure you properly cloned ImHex (using `git clone https://github.com/WerWolv/ImHex --recurse-submodules` and if that doesn't help, try uninstalling the capstone library from your system.

**Comment by Aniruddha-Deb** [comment]
Right, uninstalling capstone fixed the issue and it builds now. However I did use `--recurse-submodules`, and capstone was also built when compiling
```
[  0%] Built target fmt
[  4%] Built target libpl
[  8%] Built target imgui
[  8%] Built target microtar
[  8%] Built target generator
[ 12%] Built target libromfs
[ 12%] Built target nfd
[ 52%] Built target libcurl
[ 52%] Built target LLVMDemangle
[ 64%] Built target libyara
[ 80%] Built target capstone
[ 84%] Built target libimhex
```
 and the capstone version installed via brew is 4.0.2 (which is the latest version). Does ImHex use a nightly build of capstone? If so, how do we prefer the one in lib over the one installed in the system? (Don't want to uninstall capstone whenever I build, as I use QEMU which depends on it)

**Comment by WerWolv** [comment]
ImHex does use a nightly version because capstone didn't have a real update for the past few years.

The issue probably is that whatever you used to install capstone on your system simply shoved its includes into the system include path so the buildsystem finds that first before it finds the local copy.
I already specify my include path manually in my build script, I don't think I can do much more than that.

**Comment by WerWolv** [comment]
If you don't not having the latest and greatest features from Capstone, one thing that _should_ work too is manually setting `USE_SYSTEM_CAPSTONE` to ON in the cmake command line. Then ImHex uses the system capstone version instead.

**Comment by Aniruddha-Deb** [comment]
There's a CMake parameter called [`CMAKE_INCLUDE_DIRECTORIES_BEFORE`](https://cmake.org/cmake/help/latest/variable/CMAKE_INCLUDE_DIRECTORIES_BEFORE.html). Setting this to `ON` allows CMake to prepend rather than append our include directories to the system include path, and fixes the issue ^_^

I can submit a patch for this, but should I add this parameter to `CMakeLists.txt` across all platforms, or just on MacOS, like pass it as a command line parameter to CMake as shown in the [instructions](https://github.com/WerWolv/ImHex/blob/master/dist/compiling/macOS.md)

**Comment by WerWolv** [comment]
Oh awesome! I didn't know about that option

Feel free to add it to the actual cmake script since this issue can probably occurr on all platforms.

Here would probably be a good point to put it. If the CI manages to build it on all platforms after that it should be fine
https://github.com/WerWolv/ImHex/blob/master/CMakeLists.txt#L12-L16

Thanks a lot :)

**Comment by Aniruddha-Deb** [comment]
Sorry, (`CMAKE_INCLUDE_DIRECTORIES_BEFORE`)[https://cmake.org/cmake/help/latest/variable/CMAKE_INCLUDE_DIRECTORIES_BEFORE.html] doesn't work 😓. I wrongly assumed it worked because the compilation got past 84%, but turns out CMake just switched the order up a bit.

I'll try to find out how to prioritize local includes over system ones. Seems like a common problem and should have a fix.

**Comment by Aniruddha-Deb** [comment]
Bit of back and forth, but setting [`CMAKE_INCLUDE_DIRECTORIES_BEFORE`](https://cmake.org/cmake/help/latest/variable/CMAKE_INCLUDE_DIRECTORIES_BEFORE.html) to `ON` works. I initially thought it worked, only for it to fail (after which I deleted the comment above this) because I didn't delete the old makefiles. Cleaning out the build directory and building with freshly generated makefiles make it work.

Will submit a PR for this in a couple days, Hacktoberfest is just around the corner and would want it to be counted there :P

**Comment by WerWolv** [comment]
Cool thanks for the update!

I already opted in for this year's Hacktoberfest so feel free to PR it as soon as it's live :)
