### ISSUE TITLE
[Bug] fail to compile with commit 491ee6aa2fa80081705a840927a1653aee6ef4a0

### ISSUE THREAD

**Issue by augustheart** [WerWolv/ImHex#697]
### Operating System

Windows

### What's the issue you encountered?

```cmd
G:\Project\Code\MyProject\ImHex\plugins\builtin\source\content\views\view_pattern_editor.cpp: In member function 'void hex::plugin::builtin::ViewPatternEditor::drawPatternTooltip(pl::ptrn::Pattern*)':
G:\Project\Code\MyProject\ImHex\plugins\builtin\source\content\views\view_pattern_editor.cpp:744:78: error: no match for 'operator!=' (operand types are 'const std::optional<std::__cxx11::basic_string<char> >' and 'std::nullptr_t')
  744 |                     if (const auto &comment = pattern->getComment(); comment != nullptr) {
      |                                                                      ~~~~~~~~^~~~~~~~~~
In file included from C:/Work/msys2/mingw64/include/c++/12.1.0/x86_64-w64-mingw32/bits/c++allocator.h:33,
                 from C:/Work/msys2/mingw64/include/c++/12.1.0/bits/allocator.h:46,
                 from C:/Work/msys2/mingw64/include/c++/12.1.0/unordered_map:40,
                 from C:/Work/msys2/mingw64/include/c++/12.1.0/functional:61,
                 from G:/Project/Code/MyProject/ImHex/lib/libimhex/include/hex/ui/imgui_imhex_extensions.h:5,
                 from G:/Project/Code/MyProject/ImHex/lib/libimhex/include/hex/ui/view.hpp:8,
                 from G:/Project/Code/MyProject/ImHex/plugins/builtin/include/content/views/view_pattern_editor.hpp:3,

```

### How can the issue be reproduced?

compile with mingw64 in msys2

### ImHex Version

1.21.2

### ImHex Build Type

- [X] Nightly or built from sources

### Additional context?

mingw64 in msys2
```
$ g++ -v
Using built-in specs.
COLLECT_GCC=C:\Work\msys2\mingw64\bin\g++.exe
COLLECT_LTO_WRAPPER=C:/Work/msys2/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.1.0/lto-wrapper.exe
Target: x86_64-w64-mingw32
Configured with: ../gcc-12.1.0/configure --prefix=/mingw64 --with-local-prefix=/mingw64/local --build=x86_64-w64-mingw32 --host=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --with-native-system-header-dir=/mingw64/include --libexecdir=/mingw64/lib --enable-bootstrap --enable-checking=release --with-arch=x86-64 --with-tune=generic --enable-languages=c,lto,c++,fortran,ada,objc,obj-c++,jit --enable-shared --enable-static --enable-libatomic --enable-threads=posix --enable-graphite --enable-fully-dynamic-string --enable-libstdcxx-filesystem-ts --enable-libstdcxx-time --disable-libstdcxx-pch --enable-lto --enable-libgomp --disable-multilib --disable-rpath --disable-win32-registry --disable-nls --disable-werror --disable-symvers --with-libiconv --with-system-zlib --with-gmp=/mingw64 --with-mpfr=/mingw64 --with-mpc=/mingw64 --with-isl=/mingw64 --with-pkgversion='Rev3, Built by MSYS2 project' --with-bugurl=https://github.com/msys2/MINGW-packages/issues --with-gnu-as --with-gnu-ld --disable-libstdcxx-debug --with-boot-ldflags=-static-libstdc++ --with-stage1-ldflags=-static-libstdc++
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 12.1.0 (Rev3, Built by MSYS2 project)
```

**Comment by iTrooz** [comment]
Hey, what cmake command did you to init the build directory ? Can you try with the one in the CI ?

**Comment by WerWolv** [comment]
Hey
This looks like an issue with the git submodules this project uses. Try deleting your local repository and re-clone it again using `git clone https://github.com/WerWolv/ImHex --recurse-submodules`.
