### ISSUE TITLE
Failed to build on Ubuntu 20.04

### ISSUE THREAD

**Issue by Corfucinas** [WerWolv/ImHex#113]
```
└─> …/ImHex/build on  master via 喝 v3.16.3 
at 11:27:46 [💣 127] ✗  cmake -DCMAKE_BUILD_TYPE=Release ..
-- Checking for one of the modules 'libmagic'
CMake Error at CMakeLists.txt:47 (list):
  list index: 2 out of range (-2, 1)


-- Configuring incomplete, errors occurred!
See also "/home/the-box/Github/ImHex/build/CMakeFiles/CMakeOutput.log".
```

File is attached, thanks for taking a look! 

(I ran the bash script under build before running cmake)

[CMakeOutput.log](https://github.com/WerWolv/ImHex/files/5767944/CMakeOutput.log)

**Comment by cyang812** [comment]
I met the same issue. plz let me know how to fix it. Thanks

**Comment by aeroc7** [comment]
I just commented out line 47 and it builds successfully, though this should by no means be a permanent solution.

**Comment by Corfucinas** [comment]
I tried that now I'm having this issue

```
In file included from /home/the-box/Github/ImHex/plugins/libimhex/source/helpers/utils.cpp:1:
/home/the-box/Github/ImHex/plugins/libimhex/include/helpers/utils.hpp:62:10: fatal error: concepts: No such file or directory
   62 | #include <concepts>
      |          ^~~~~~~~~~
compilation terminated.
make[2]: *** [plugins/libimhex/CMakeFiles/libimhex.dir/build.make:76: plugins/libimhex/CMakeFiles/libimhex.dir/source/helpers/utils.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:215: plugins/libimhex/CMakeFiles/libimhex.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

```

**Comment by aeroc7** [comment]
> 
> 
> I tried that now I'm having this issue
> 
> ```
> In file included from /home/the-box/Github/ImHex/plugins/libimhex/source/helpers/utils.cpp:1:
> /home/the-box/Github/ImHex/plugins/libimhex/include/helpers/utils.hpp:62:10: fatal error: concepts: No such file or directory
>    62 | #include <concepts>
>       |          ^~~~~~~~~~
> compilation terminated.
> make[2]: *** [plugins/libimhex/CMakeFiles/libimhex.dir/build.make:76: plugins/libimhex/CMakeFiles/libimhex.dir/source/helpers/utils.cpp.o] Error 1
> make[2]: *** Waiting for unfinished jobs....
> make[1]: *** [CMakeFiles/Makefile2:215: plugins/libimhex/CMakeFiles/libimhex.dir/all] Error 2
> make: *** [Makefile:130: all] Error 2
> ```

Read the README. You need a C++20 compiler, like GCC 10.2.0

**Comment by Corfucinas** [comment]
I do have g++-10 installed (ran the get_deps_debian.sh).

Also exported the CXX=g++-10 to ./bash

**Comment by Corfucinas** [comment]
NVM, fixed.

Had to delete de "CmakeCache.txt" under /build

**Comment by Corfucinas** [comment]
> I do have g++-10 installed (ran the get_deps_debian.sh).
> 
> Also exported the CXX=g++-10 to ./bash

Had to delete the "CmakeCache.txt" under build.

Now I got a new error

```

[100%] Linking CXX executable imhex
/usr/bin/ld: /home/the-box/.pyenv/versions/3.9.1/lib/libpython3.9.a(thread.o): undefined reference to symbol 'pthread_condattr_setclock@@GLIBC_2.3.3'
/usr/bin/ld: /lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/imhex.dir/build.make:481: imhex] Error 1
make[1]: *** [CMakeFiles/Makefile2:160: CMakeFiles/imhex.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

```

**Comment by aeroc7** [comment]
> > I do have g++-10 installed (ran the get_deps_debian.sh).
> > Also exported the CXX=g++-10 to ./bash
> 
> Had to delete the "CmakeCache.txt" under build.
> 
> Now I got a new error
> 
> ```
> 
> [100%] Linking CXX executable imhex
> /usr/bin/ld: /home/the-box/.pyenv/versions/3.9.1/lib/libpython3.9.a(thread.o): undefined reference to symbol 'pthread_condattr_setclock@@GLIBC_2.3.3'
> /usr/bin/ld: /lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
> collect2: error: ld returned 1 exit status
> make[2]: *** [CMakeFiles/imhex.dir/build.make:481: imhex] Error 1
> make[1]: *** [CMakeFiles/Makefile2:160: CMakeFiles/imhex.dir/all] Error 2
> make: *** [Makefile:130: all] Error 2
> ```

I'm on Ubuntu 20.10 and installed the needed dependencies and built successfully sans the CMake issue. Perhaps add -lpthread to your linker options and try again?

**Comment by Corfucinas** [comment]
@aeroc7 

What version of Python you have and how to do manage it? Apt? I have pyenv...not sure If it's related to that.

What command would you use to compile it based on your observation? Not sure I managed to grasp what you were saying.

**Comment by aeroc7** [comment]
> @aeroc7
> 
> What version of Python you have and how you manage it? Apt? I have pyenv...not sure If it's related to that.
> 
> What command would you use to compile it based on your observation? Not sure I managed to grasp what you were saying.

sudo apt-get install python3.8

**Comment by Corfucinas** [comment]
I do have it

```
at 11:43:10 ➜ which python3.8
/usr/bin/python3.8
```

**Comment by Calinou** [comment]
@Corfucinas Are you still running into this issue with the latest `master` branch?

**Comment by Corfucinas** [comment]
@Calinou 

I just pulled and try to build, got the following error

```
at 11:32:36 ➜ cmake -DCMAKE_BUILD_TYPE=Release ..
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 10.2.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/g++-10
-- Check for working CXX compiler: /usr/bin/g++-10 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for one of the modules 'capstone'
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libOpenGL.so   
-- Found Python: /home/the-box/.pyenv/versions/3.9.1/lib/libpython3.9.a (found version "3.9") found components: Development 
-- Checking for one of the modules 'libmagic'
-- Found Freetype: /usr/lib/x86_64-linux-gnu/libfreetype.so (found version "2.10.1") 
-- Checking for one of the modules 'glm'
-- Checking for one of the modules 'glfw3'
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
/home/the-box/Github/ImHex/plugins/libimhex/MBEDTLS_INCLUDE_DIR
   used as include directory in directory /home/the-box/Github/ImHex/plugins/libimhex

-- Configuring incomplete, errors occurred!
See also "/home/the-box/Github/ImHex/build/CMakeFiles/CMakeOutput.log".
```

Not sure if you can identify the problem or need the `cmakeoutput.log`

**Comment by WerWolv** [comment]
The master branch is generally unstable. Don't expect it to build while I'm working on new features. You can also check the build-status indicator in the Readme to see if the latest commits are building.
